
name: FACTORY-DISPATCH

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # every day at midnight
    
jobs:
  prepare:
    if: ${{ !contains(github.event.head_commit.message, '#NOCI') }}
    runs-on: ubuntu-latest

    outputs:
      imageMatrix: ${{ steps.set-imageMatrix.outputs.matrix }}
      imageVersion: ${{ steps.set-imageVersion.outputs.version }}

    steps:

      - name: Download Source
        uses: actions/checkout@v4

      - name: Generate Image Matrix
        id: set-imageMatrix
        run: |
          echo "matrix=$(find . -type f -name 'image.json' | sed -r 's|/[^/]+$||' | sort -u | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT      
          cat $GITHUB_OUTPUT

      - name: Generate Image Version
        id: set-imageVersion
        run: |
          echo "version=$(date -u +'%Y.%m%d.%H%M')" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT

  dispatch:
    needs: prepare
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      
    strategy:
      fail-fast: false
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.imageMatrix) }} 

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.image }}

    steps:

      - name: Download Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Resolve Image Information
        id: image
        run: |
          echo "imageCommit=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "imageName=$(basename "${{ matrix.image }}")" >> $GITHUB_OUTPUT
          if git diff --name-only HEAD^ HEAD | grep -q "^/$(echo '${{ matrix.image }}' | sed 's|^\.*||')"; then
            echo "imageChanged=true" >> $GITHUB_OUTPUT
          else
            echo "imageChanged=false" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

      - name: Trigger Image Build
        uses: actions/github-script@v7
        if: github.event_name == 'schedule' || contains(steps.image.outputs.imageCommit, '#FORCE') || steps.image.outputs.imageChanged == 'true'
        with:
          debug: true
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build-image.yml',
              ref: 'main',
              inputs: {
                imageName: '${{ steps.image.outputs.imageName }}',
                imageVersion: '${{ needs.prepare.outputs.imageVersion }}'
              },
            })

  
